// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Language } from "./Language";
import type { Theme } from "./Theme";

export type Appearance = { theme: Theme, language: Language, };
