// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Appearance } from "./Appearance";
import type { Interaction } from "./Interaction";
import type { Pagination } from "./Pagination";
import type { Profile } from "./Profile";
import type { SystemConfig } from "./SystemConfig";

export type Config = { version: number, activeProfileId: string, profiles: Array<Profile>, appearance: Appearance, interaction: Interaction, pagination: Pagination, system: SystemConfig, };
