// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Appearance } from "./Appearance";
import type { Interaction } from "./Interaction";
import type { Pagination } from "./Pagination";
import type { SystemConfig } from "./SystemConfig";
import type { Tab } from "./Tab";

export type Config = { version: number, shortcut: string, appearance: Appearance, interaction: Interaction, pagination: Pagination, system: SystemConfig, tabs: Array<Tab>, };
