// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FaviconResult = { 
/**
 * Absolute path to the cached file. Frontend must use Tauri's
 * `convertFileSrc` to render it inside the webview.
 */
localPath: string, mime: string, };
