// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Config } from "./Config";

/**
 * Resultado do `import_config`: a config nova já em vigor + flag indicando
 * se o atalho global foi re-registrado com sucesso. `false` significa que
 * a config foi gravada/carregada mas o combo do novo perfil ativo colidiu
 * com outro app — o atalho anterior segue bound até reinício.
 */
export type ImportResult = { config: Config, shortcutReconciled: boolean, };
