// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstalledApp = { 
/**
 * Nome amigável que o usuário copia/seleciona pra `Item::App.name`.
 * macOS: stem do `.app` bundle (`"Firefox"`).
 * Linux: `Name=` do `.desktop`.
 * Windows: stem do exe (App Paths) ou do `.lnk` (Start Menu).
 */
name: string, 
/**
 * Caminho absoluto do binário/bundle/lnk. Informacional — não é usado
 * pelo launcher (que invoca `name`), mas ajuda picker a desambiguar
 * duplicatas e mostrar tooltip futuro.
 */
path: string, };
