// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstalledApp = { 
/**
 * Display friendly mostrado como título da row no picker.
 * macOS: stem do `.app` bundle (`"Firefox"`).
 * Linux: `Name=` do `.desktop`.
 * Windows: stem do exe (App Paths) ou do `.lnk` (Start Menu).
 */
name: string, 
/**
 * String que o picker insere em `Item::App.name` quando o user seleciona
 * a row. Varia por SO pra casar com o launcher do Plano 14 — ver doc do
 * módulo. **AppPicker.onSelect dispatch this, not `name`.**
 */
value: string, 
/**
 * Caminho informacional (subtitle/tooltip + desambiguação de duplicatas).
 * macOS: bundle path. Linux: `.desktop` file path. Windows: mesmo que
 * `value` (sempre path absoluto naquele ramo).
 */
path: string, };
