// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectionMode } from "./SelectionMode";
import type { SpawnPosition } from "./SpawnPosition";

export type Interaction = { spawnPosition: SpawnPosition, selectionMode: SelectionMode, hoverHoldMs: number, 
/**
 * Atalho window-level que abre o overlay de busca rápida no donut.
 * Formato Tauri (`CommandOrControl+F`). Configs do Plano 12 ou
 * anteriores deserializam usando `default_search_shortcut`.
 */
searchShortcut: string, };
