// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectionMode } from "./SelectionMode";
import type { SpawnPosition } from "./SpawnPosition";

export type Interaction = { spawnPosition: SpawnPosition, selectionMode: SelectionMode, hoverHoldMs: number, };
