// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectionMode } from "./SelectionMode";
import type { SpawnPosition } from "./SpawnPosition";

export type Interaction = { spawnPosition: SpawnPosition, selectionMode: SelectionMode, hoverHoldMs: number, 
/**
 * Atalho window-level que abre o overlay de busca rápida no donut.
 * Formato Tauri (`CommandOrControl+F`). Configs do Plano 12 ou
 * anteriores deserializam usando `default_search_shortcut`.
 */
searchShortcut: string, 
/**
 * Plano 23 — quando `true` (default), o donut pinta gap angular
 * entre slices vizinhos. Quando `false`, slices ficam coladas (look
 * original Plano 16). Configs anteriores deserializam como `true`
 * graças ao `#[serde(default = "default_slice_gap_enabled")]`.
 */
sliceGapEnabled: boolean, 
/**
 * Issue #71 — "modo rápido". Quando `true`, o donut só fica visível
 * enquanto o atalho global estiver pressionado: soltar a tecla abre
 * a aba sob o cursor (se houver) e esconde o donut. Default `false`
 * preserva o comportamento click-to-open. Configs anteriores
 * deserializam como `false` graças ao
 * `#[serde(default)]` (bool default). Wire: `quickMode` (camelCase).
 */
quickMode: boolean, };
