// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Item = { "kind": "url", value: string, openWith: string | null, 
/**
 * Plano 21 — índice 0-based do monitor alvo. `None` = OS default
 * (atual monitor do cursor / janela existente). Quando `Some`, o
 * launcher dispara cursor warp pro centro do monitor antes de abrir,
 * que faz a maioria dos browsers/apps abrir nessa tela. Apps que
 * reusam janela existente podem ignorar. Configs anteriores
 * deserializam como `None` graças ao `#[serde(default)]`.
 */
monitor: number | null, } | { "kind": "file", path: string, openWith: string | null, monitor: number | null, } | { "kind": "folder", path: string, openWith: string | null, monitor: number | null, } | { "kind": "app", name: string, monitor: number | null, } | { "kind": "script", command: string, trusted: boolean, monitor: number | null, };
