// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Item = { "kind": "url", value: string, openWith: string | null, } | { "kind": "file", path: string, openWith: string | null, } | { "kind": "folder", path: string, openWith: string | null, };
