// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Plano 21 — info do monitor pra picker no Settings. Frontend usa pra
 * renderizar `<select>` por item; quando `len() <= 1` esconde a coluna.
 */
export type MonitorInfo = { 
/**
 * Nome amigável reportado pelo SO (ou `"Tela {N}"` quando vazio).
 */
name: string, 
/**
 * Índice 0-based — espelha a ordem de `available_monitors()` e é o
 * valor que vai pro `Item.monitor`.
 */
index: number, width: number, height: number, x: number, y: number, 
/**
 * `true` quando este monitor é o primário do SO. Usado pra marcar a
 * option-default no picker (ex.: "Tela 1 (primária)").
 */
primary: boolean, };
