// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WheelDirection } from "./WheelDirection";

export type Pagination = { itemsPerPage: number, wheelDirection: WheelDirection, };
