// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tab } from "./Tab";
import type { Theme } from "./Theme";

export type Profile = { id: string, name: string, icon: string | null, shortcut: string, theme: Theme, tabs: Array<Tab>, };
