// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tab } from "./Tab";
import type { Theme } from "./Theme";
import type { ThemeOverrides } from "./ThemeOverrides";

export type Profile = { id: string, name: string, icon: string | null, shortcut: string, theme: Theme, tabs: Array<Tab>, 
/**
 * Kill-switch global por perfil para items `kind: "script"`. Default
 * `false` (princípio do menor privilégio). Quando `false`, o launcher
 * bloqueia toda execução de script no perfil — independente do flag
 * `trusted` do item — e o frontend mostra erro localizado em vez do
 * modal de confirmação. Plano-13 e configs anteriores deserializam
 * como `false` graças ao `#[serde(default)]`.
 */
allowScripts: boolean, 
/**
 * Plano 15 — overrides cosméticos que se aplicam por cima do preset
 * `theme` (cores, transparência do overlay, ratios de raio interno/
 * externo). `None` = usa apenas o preset. Cada campo de cor/dimensão
 * dentro do struct também é `Option`, então o usuário customiza só
 * um subset. Configs Plano-14 e anteriores deserializam como `None`
 * graças ao `#[serde(default)]`.
 */
themeOverrides: ThemeOverrides | null, };
