// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScriptStatus } from "./ScriptStatus";

/**
 * Shape leve consumido pela lista de runs no `<HistorySection>` —
 * evita transferir o output completo na list view.
 */
export type ScriptRunSummary = { id: string, profileId: string, tabId: string, command: string, startedAt: number, finishedAt: number | null, exitCode: number | null, status: ScriptStatus, truncated: boolean, };
