// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Estado terminal (ou em curso) de uma execução de script.
 */
export type ScriptStatus = "running" | "succeeded" | "failed" | "interrupted" | "cancelled";
