// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScriptStatus } from "./ScriptStatus";

/**
 * Entrada completa do histórico — detail view do `<HistorySection>`.
 * Buffer in-memory only; nunca persistido em disco (output pode conter
 * secrets).
 */
export type ScriptRun = { id: string, profileId: string, tabId: string, itemIndex: number, command: string, 
/**
 * Unix epoch millis. Frontend converte pra timezone local via `new Date()`.
 * `#[ts(type = "number")]` força a binding pra `number` (ts-rs default
 * pra `i64` é `bigint` — incompatível com `new Date()`).
 */
startedAt: number, finishedAt: number | null, exitCode: number | null, stdout: string, stderr: string, 
/**
 * `true` quando algum dos streams atingiu o cap (linhas ou bytes).
 */
truncated: boolean, status: ScriptStatus, };
