// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stream de origem de um chunk de output. Frontend usa pra dirigir
 * painéis stdout/stderr separados.
 */
export type ScriptStream = "stdout" | "stderr";
