// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SystemConfig = { autostart: boolean, 
/**
 * Plano 18 — quando `true`, a app dispara um check de atualização no
 * startup e exibe notificação OS-native (uma única vez por versão
 * remota nova) caso encontre versão maior. Default `true`. Configs
 * Plano-17 e anteriores deserializam com `true` graças ao
 * `#[serde(default = "default_auto_check_updates")]`.
 */
autoCheckUpdates: boolean, 
/**
 * Plano 18 — última versão pra qual o usuário já recebeu a
 * notificação OS-native no startup. Gate `should_notify` evita
 * re-notificar a mesma versão. Field é estado interno persistido pelo
 * updater; user pode editar manualmente sem efeito colateral
 * (resetar = re-notifica). `None` em configs Plano-17 e anteriores;
 * `skip_serializing_if = "Option::is_none"` mantém o JSON enxuto
 * enquanto nenhum check rodou.
 */
lastNotifiedUpdateVersion: string | null, };
