// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Item } from "./Item";
import type { OpenMode } from "./OpenMode";
import type { TabKind } from "./TabKind";

export type Tab = { id: string, name: string | null, icon: string | null, order: number, openMode: OpenMode, items: Array<Item>, 
/**
 * Plano 16 — sub-donuts. Quando `kind == Group`, esta aba abre um
 * sub-donut com `children`; quando `kind == Leaf`, abre os `items`.
 * `#[serde(default)]` faz configs Plano-15 carregarem como `Leaf` sem
 * migração; `skip_serializing_if = is_leaf_kind` mantém o JSON enxuto
 * pra leaves (caso comum). Persistir o kind explicitamente resolve o
 * caso ambíguo de tab vazia (items=[] && children=[]) — sem isso,
 * não há como distinguir um group vazio de um leaf vazio depois do
 * round-trip.
 */
kind: TabKind, 
/**
 * Plano 16 — sub-donuts. Quando `kind == Group`, lista os filhos
 * (vazio é permitido como draft). Quando `kind == Leaf`, deve ser
 * vazio (validate rejeita). `#[serde(default, skip_serializing_if =
 * "Vec::is_empty")]` mantém configs Plano-15 carregando sem migração
 * e não polui JSON de leaves.
 */
children: Array<Tab>, };
