// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Item } from "./Item";
import type { OpenMode } from "./OpenMode";

export type Tab = { id: string, name: string | null, icon: string | null, order: number, openMode: OpenMode, items: Array<Item>, };
