// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThemeColors = { sliceFill: string | null, sliceHighlight: string | null, sliceStroke: string | null, centerFill: string | null, text: string | null, };
