// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resumo de uma atualização disponível devolvido pelo plugin updater.
 * Frontend consome via comandos Tauri pra renderizar banner/notification.
 */
export type UpdateSummary = { version: string, notes: string | null, date: string | null, };
